import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
    en: {
        home: "Home",
        companies: "Companies",
        login: "Login",
        register: "Register",
        hello: "Hello",
        logout: "Logout",
        yourCompanies: "Your companies",
        createNew: "Create new",
        shopName: "Shop name",
        country: "Country",
        actions: "Actions",
        shops: "shops",
        state: "State",
        city: "City",
        address1: "Address1",
        address2: "Address2",
        products: "products",
        name: "Name",
        description: "Description",
        price: "Price",
        submit: "Submit",
    },
    ua: {
        home: "Домашня",
        companies: "Компанії",
        login: "Вход",
        register: "Реєстрація",
        hello: "Привіт",
        logout: "Вийти",
        yourCompanies: "Ваші компанії",
        createNew: "Створити нову",
        shopName: "Назва магазину",
        country: "Країна",
        actions: "Дії",
        shops: "крамниці",
        state: "Область",
        city: "Місто",
        address1: "Адреса1",
        address2: "Адреса2",
        products: "товари",
        name: "Назва",
        description: "Опис",
        price: "Ціна",
        submit: "Підтвердити",
    }
});

export default strings;