import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
    en: {
        home: "Home",
        companies: "Companies",
        login: "Login",
        register: "Register",
        hello: "Hello",
        logout: "Logout",
        yourCompanies: "Your companies",
        createNew: "Create new",
        companyName: "Company name",
        country: "Country",
        actions: "Actions",
        shops: "shops",
        shopName: "Shop name",
        state: "State",
        city: "City",
        address1: "Address1",
        address2: "Address2",
        products: "products",
        name: "Name",
        description: "Description",
        price: "Price",
        submit: "Submit",
        confirmToSubmit: "Confirm to submit",
        deleteCompanyMessage: "Are you sure you want to delete this company?",
        deleteProductMessage: "Are you sure you want to delete this product?",
        deleteShopMessage: "Are you sure you want to delete this shop?",
        yes: "Yes",
        no: "No",
        shopManagerId: "Shop manager ID",
    },
    ua: {
        home: "Домашня",
        companies: "Компанії",
        login: "Вход",
        register: "Реєстрація",
        hello: "Привіт",
        logout: "Вийти",
        yourCompanies: "Ваші компанії",
        createNew: "Створити нову",
        companyName: "Назва компанії",
        country: "Країна",
        actions: "Дії",
        shops: "крамниці",
        shopName: "Назва крамниці",
        state: "Область",
        city: "Місто",
        address1: "Адреса1",
        address2: "Адреса2",
        products: "товари",
        name: "Назва",
        description: "Опис",
        price: "Ціна",
        submit: "Підтвердити",
        confirmToSubmit: "Підтвердження",
        deleteCompanyMessage: "Ви впевнені, що бажаєте видалити цю компанію?",
        deleteProductMessage: "Ви впевнені, що бажаєте видалити цей товар?",
        deleteShopMessage: "Ви впевнені, що бажаєте видалити цю крамницю?",
        yes: "Так",
        no: "Ні",
        shopManagerId: "ID менеджера",
    }
});

export default strings;