import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
    en: {
        home: "Home",
        companies: "Companies",
        login: "Login",
        register: "Register",
        hello: "Hello",
        logout: "Logout",
        yourCompanies: "Your companies",
        createNew: "Create new",
        companyName: "Company name",
        country: "Country",
        actions: "Actions",
        shops: "shops",
        shop: "Shop",
        shopName: "Shop name",
        state: "State",
        city: "City",
        address1: "Address1",
        address2: "Address2",
        products: "products",
        name: "Name",
        description: "Description",
        price: "Price",
        submit: "Submit",
        confirmToSubmit: "Confirm to submit",
        deleteCompanyMessage: "Are you sure you want to delete this company?",
        deleteProductMessage: "Are you sure you want to delete this product?",
        deleteShopMessage: "Are you sure you want to delete this shop?",
        deleteAttRequestMessage: "Are you sure you want to delete this attention request?",
        resolveAttRequestMessage: "Are you sure you want to resolve this attention request?",
        deletePurchaseMessage: "Are you sure you want to delete this purchase?",
        deletePurchaseDetailMessage: "Are you sure you want to delete this purchase detail?",
        yes: "Yes",
        no: "No",
        shopManagerId: "Shop manager ID",
        requests: "requests",
        message: "Message",
        isResolved: "Is resolved",
        createdDate: "Creation date",
        resolveDate: "Resolve date",
        purchases: "purchases",
        createdBy: "Created by",
        startPurchaseTime: "Start purchase time",
        finishPurchaseTime: "Finish purchase time",
        purchase: "Purchase",
        details: "details",
        product: "Product",
        amount: "Amount",
    },
    ua: {
        home: "Домашня",
        companies: "Компанії",
        login: "Вход",
        register: "Реєстрація",
        hello: "Привіт",
        logout: "Вийти",
        yourCompanies: "Ваші компанії",
        createNew: "Створити нову",
        companyName: "Назва компанії",
        country: "Країна",
        actions: "Дії",
        shops: "крамниці",
        shop: "Крамниця",
        shopName: "Назва крамниці",
        state: "Область",
        city: "Місто",
        address1: "Адреса1",
        address2: "Адреса2",
        products: "товари",
        name: "Назва",
        description: "Опис",
        price: "Ціна",
        submit: "Підтвердити",
        confirmToSubmit: "Підтвердження",
        deleteCompanyMessage: "Ви впевнені, що бажаєте видалити цю компанію?",
        deleteProductMessage: "Ви впевнені, що бажаєте видалити цей товар?",
        deleteShopMessage: "Ви впевнені, що бажаєте видалити цю крамницю?",
        deleteAttRequestMessage: "Ви впевнені, що бажаєте видалити цей запит?",
        resolveAttRequestMessage: "Ви впевнені, що бажаєте закрити цей запит?",
        deletePurchaseMessage: "Ви впевнені, що бажаєте видалити цю покупку?",
        deletePurchaseDetailMessage: "Ви впевнені, що бажаєте видалити цю деталь покупки?",
        yes: "Так",
        no: "Ні",
        shopManagerId: "ID менеджера",
        requests: "запити",
        message: "Повідомлення",
        isResolved: "Чи закрито",
        createdDate: "Час створення",
        resolveDate: "Час закриття",
        purchases: "purchases",
        createdBy: "Створено",
        startPurchaseTime: "Час початку",
        finishPurchaseTime: "Час закінчення",
        purchase: "Покупка",
        details: "деталі",
        product: "Продукт",
        amount: "Кількість",
    }
});

export default strings;